### ISSUE TITLE
little issue with new stable js-controller 3.3.15

### ISSUE THREAD

**Issue by jlegen** [MK-2001/ioBroker.go-e#76] opened 2021-08-07 12:16 UTC
log gets filled up with:

2021-08-07 14:16:06.289  - info: go-e.0 (6496) State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"

**Comment by weindler** [comment] 2021-08-08 11:37
Here is the same, please fix it, thanks

**Comment by MK-2001** [comment] 2021-08-08 14:04
Seems to be only at Versuon 3 Hardware. This HW is currently not available to test it. Bug will be on hold.

**Comment by jlegen** [comment] 2021-08-08 20:11
I have a V2 hardware; i think the easy fix is to replace
await queue.add(() => this.setState("temperatures.tempereatureArray",     { val: o.tma, ack: true }));
with
await queue.add(() => this.setState("temperatures.tempereatureArray",     { val: JSON.stringify(o.tma), ack: true }));

in main.js; messages are gone…

**Comment by MK-2001** [comment] 2021-08-09 08:54
Hi and thank you Jlegen. 
Currently all people have used for their Adapter settings and may be temperatures alarms methods to act on arrays. If I now will switch to an Object or to an string as you suggest above it will be a breaking change and many scripts will fail.  

This bug needs a deeper analyst why the adapter is sending here a object instead of the array.

This bug will be on hold until the hardware and firmware is in place.

Kind regards

**Comment by jlegen** [comment] 2021-08-09 12:25
Hi, i'm not an "iobroker adapter expert", but i honestly don't think that this fix changes anything for applications apart from the annoying log records. 
As i understand, without the fix js-controller is doing the type conversion automatically (as it did this before, but silently), and version 3.3 now throws the warning to encourage explicit type conversion. Which is what the fix does, imo...

Anyway, the contents of the data point (tempereatureArray) *before* the fix was "[22.88,21.38,21.38,21.75]", and it is now "[22.88,21.38,21.38,21.75]" after the fix. Not sure why/what apps may break now...

**Comment by GoClyde** [comment] 2021-09-17 08:26
Same here with V2 Hardware

**Comment by Homoran** [comment] 2021-12-30 20:29
It's still that issue - only the mentioned state with a wrong type

I also don't have a v3, but a v2 go-e Charger

**Comment by micklafisch** [comment] 2022-01-05 10:07
i have the same error with my new v3 go-e Charger

so how to handle that issue in future? fix from jlegen or change the loglevel of the adapter to error or update from the go-e adapter (which in my opinion is the cleanest solution)?

**Comment by MK-2001** [comment] 2022-01-21 20:36
Duplicate of #91. Please switch it off in the settings menu. 

In der letzten Version auf dem Stable kann das Schreiben des Tempera deaktiviert werden, damit erscheinen die object<<=>string Warnungen nicht mehr.

**Closed by MK-2001** 2022-01-21 20:36 UTC
