### ISSUE TITLE
info in ioBroker go-e.0.temperatures.tempereatureArray

### ISSUE THREAD

**Issue by Wolfling78** [MK-2001/ioBroker.go-e#105] opened 2022-01-20 06:42 UTC
**Describe the bug**  
State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"

Ich habe Hardware V2 und Firmware 041.0

**Comment by MK-2001** [comment] 2022-01-21 20:33
This is a duplicate of #91. Please switch it off in the settings menu.

**Closed by MK-2001** 2022-01-21 20:33 UTC
